title: 王杰-Jie Wang
description: 王杰的主页.
author: 王杰 Jie Wang
avatar: /logo.jpeg
email: jie.wang@ruc.edu.cn

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.jpeg
social:
  name: Jie Wang
  links:
    # - https://twitter.com/ngzhio
    # - https://www.facebook.com/ngzhio
    - https://github.com/wangjie-ruc 
    - https://weibo.com/u/3621391992
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
google-site-verification: jth8J-966Q629_Fw41dtqQqmoTvMKYD6s_OUD-rI-80
lang: en